version: '3'

vars:
  OVERLEAF_DIR: overleaf
  TOOLKIT_DIR: overleaf-toolkit
  SHARELATEX_TAG: with-texlive-full
  TOOLKIT_DEFAULT_VERSION: 6.0.1
  GNU_SED_PATH:
    sh: |
      if [ -d /opt/homebrew/opt/gnu-sed/libexec/gnubin ]; then
        echo /opt/homebrew/opt/gnu-sed/libexec/gnubin
      elif [ -d /usr/local/opt/gnu-sed/libexec/gnubin ]; then
        echo /usr/local/opt/gnu-sed/libexec/gnubin
      fi

env:
  PATH: '{{if .GNU_SED_PATH}}{{.GNU_SED_PATH}}:{{end}}{{.PATH}}'

tasks:
  default:
    desc: Clone, build, and start Overleaf CE locally
    cmds:
      - task: up

  clone:
    desc: Clone Overleaf CE and toolkit repositories if missing
    cmds:
      - |
        if [ -e "{{.OVERLEAF_DIR}}" ] && [ ! -d "{{.OVERLEAF_DIR}}" ]; then
          echo "error: {{.OVERLEAF_DIR}} がディレクトリ以外として存在しています。削除または移動してください。" >&2
          exit 1
        fi
        [ -d "{{.OVERLEAF_DIR}}" ] || git clone https://github.com/overleaf/overleaf "{{.OVERLEAF_DIR}}"
      - |
        if [ -e "{{.TOOLKIT_DIR}}" ] && [ ! -d "{{.TOOLKIT_DIR}}" ]; then
          echo "error: {{.TOOLKIT_DIR}} がディレクトリ以外として存在しています。削除または移動してください。" >&2
          exit 1
        fi
        [ -d "{{.TOOLKIT_DIR}}" ] || git clone https://github.com/overleaf/toolkit.git "{{.TOOLKIT_DIR}}"

  build:
    desc: Build Overleaf CE base and community images
    cmds:
      - |
        if [ ! -d "{{.OVERLEAF_DIR}}/server-ce" ]; then
          echo "error: {{.OVERLEAF_DIR}}/server-ce が見つかりません。先に task clone を実行してください。" >&2
          exit 1
        fi
      - cd "{{.OVERLEAF_DIR}}/server-ce" && make build-base
      - cd "{{.OVERLEAF_DIR}}/server-ce" && make build-community

  toolkit_init:
    desc: Initialize Overleaf toolkit and start containers
    cmds:
      - |
        if [ ! -d "{{.TOOLKIT_DIR}}" ]; then
          echo "error: {{.TOOLKIT_DIR}} が見つかりません。先に task clone を実行してください。" >&2
          exit 1
        fi
      - |
        if [ "$(uname)" = "Darwin" ] && ! command -v gsed >/dev/null 2>&1; then
          echo "error: macOS では GNU sed (gsed) が必要です。brew install gnu-sed を実行してください。" >&2
          exit 1
        fi
      - |
        if [ ! -f "{{.TOOLKIT_DIR}}/config/overleaf.rc" ]; then
          export PATH="{{if .GNU_SED_PATH}}{{.GNU_SED_PATH}}:{{end}}{{.PATH}}"
          bash -c 'cd "{{.TOOLKIT_DIR}}" && bin/init'
        else
          echo "config already exists, skip bin/init"
        fi
      - |
        if [ "$(uname)" = "Darwin" ] && [ "$(uname -m)" = "arm64" ]; then
          version_file="{{.TOOLKIT_DIR}}/config/version"
          current_version=""
          [ -f "$version_file" ] && current_version=$(head -n 1 "$version_file")
          if ! expr "$current_version" : '^[0-9]\+\.[0-9]\+\.[0-9]\+' >/dev/null; then
            echo "config/version が不正値 (${current_version:-<empty>}) のため {{.TOOLKIT_DEFAULT_VERSION}} にリセットします" >&2
            current_version="{{.TOOLKIT_DEFAULT_VERSION}}"
            echo "$current_version" > "$version_file"
          fi
          if docker image inspect sharelatex/sharelatex:main >/dev/null 2>&1; then
            echo "Tagging local sharelatex/sharelatex:main -> sharelatex/sharelatex:$current_version (arm64 用)" >&2
            docker tag sharelatex/sharelatex:main "sharelatex/sharelatex:$current_version"
          else
            echo "warning: sharelatex/sharelatex:main がありません。先に make build-community を実行してください。" >&2
          fi
        fi
      - cd "{{.TOOLKIT_DIR}}" && mkdir -p data/sharelatex data/mongo data/redis data/nginx
      - cmd: |
          export PATH="{{if .GNU_SED_PATH}}{{.GNU_SED_PATH}}:{{end}}{{.PATH}}"
          bash -c 'cd "{{.TOOLKIT_DIR}}" && bin/up'
        env:
          PATH: '{{if .GNU_SED_PATH}}{{.GNU_SED_PATH}}:{{end}}{{.PATH}}'

  toolkit_texlive:
    desc: Update TeX Live repositories and install scheme-full in the sharelatex container
    cmds:
      - docker exec sharelatex tlmgr update --self
      - docker exec sharelatex tlmgr install scheme-full xstring collection-luatex collection-langjapanese xkeyval

  toolkit_commit_image:
    desc: Commit sharelatex container to sharelatex/sharelatex:{{.SHARELATEX_TAG}}
    cmds:
      - |
        if ! docker ps --format '{{"{{.Names}}"}}' | grep -q '^sharelatex$'; then
          echo "error: sharelatex コンテナが起動していません。bin/up 後に実行してください。" >&2
          exit 1
        fi
        docker commit sharelatex "sharelatex/sharelatex:{{.SHARELATEX_TAG}}"

  toolkit_patch_compose:
    desc: Rewrite overleaf-toolkit/lib/shared-functions.sh to use tag {{.SHARELATEX_TAG}}
    cmds:
      - |
        file="{{.TOOLKIT_DIR}}/lib/shared-functions.sh"
        if [ ! -f "$file" ]; then
          echo "error: $file が見つかりません。先に task clone を実行してください。" >&2
          exit 1
        fi
        old='export IMAGE="$image_name:$version"'
        new='export IMAGE="$image_name:{{.SHARELATEX_TAG}}"'
        if grep -qF "$new" "$file"; then
          echo "already patched"
          exit 0
        fi
        if ! grep -qF "$old" "$file"; then
          echo "error: target line not found. manual check needed." >&2
          exit 1
        fi
        perl -0pi -e 's/export IMAGE="[^"]*"/export IMAGE="\\$image_name:{{.SHARELATEX_TAG}}"/' "$file"

  toolkit_restart:
    desc: Restart overleaf using toolkit (bin/stop && bin/up)
    cmds:
      - |
        if [ "$(uname)" = "Darwin" ] && ! command -v gsed >/dev/null 2>&1; then
          echo "error: macOS では GNU sed (gsed) が必要です。brew install gnu-sed を実行してください。" >&2
          exit 1
        fi
      - cmd: |
          export PATH="{{if .GNU_SED_PATH}}{{.GNU_SED_PATH}}:{{end}}{{.PATH}}"
          bash -c 'cd "{{.TOOLKIT_DIR}}" && bin/stop'
        env:
          PATH: '{{if .GNU_SED_PATH}}{{.GNU_SED_PATH}}:{{end}}{{.PATH}}'
      - cmd: |
          export PATH="{{if .GNU_SED_PATH}}{{.GNU_SED_PATH}}:{{end}}{{.PATH}}"
          bash -c 'cd "{{.TOOLKIT_DIR}}" && bin/up'
        env:
          PATH: '{{if .GNU_SED_PATH}}{{.GNU_SED_PATH}}:{{end}}{{.PATH}}'

  toolkit_stop:
    desc: Stop overleaf toolkit containers
    cmds:
      - |
        if [ "$(uname)" = "Darwin" ] && ! command -v gsed >/dev/null 2>&1; then
          echo "error: macOS では GNU sed (gsed) が必要です。brew install gnu-sed を実行してください。" >&2
          exit 1
        fi
      - cmd: |
          export PATH="{{if .GNU_SED_PATH}}{{.GNU_SED_PATH}}:{{end}}{{.PATH}}"
          bash -c 'cd "{{.TOOLKIT_DIR}}" && bin/stop'
        env:
          PATH: '{{if .GNU_SED_PATH}}{{.GNU_SED_PATH}}:{{end}}{{.PATH}}'

  toolkit_start:
    desc: Start overleaf toolkit containers (no rebuild)
    cmds:
      - |
        if [ "$(uname)" = "Darwin" ] && ! command -v gsed >/dev/null 2>&1; then
          echo "error: macOS では GNU sed (gsed) が必要です。brew install gnu-sed を実行してください。" >&2
          exit 1
        fi
      - cmd: |
          export PATH="{{if .GNU_SED_PATH}}{{.GNU_SED_PATH}}:{{end}}{{.PATH}}"
          bash -c 'cd "{{.TOOLKIT_DIR}}" && bin/start'
        env:
          PATH: '{{if .GNU_SED_PATH}}{{.GNU_SED_PATH}}:{{end}}{{.PATH}}'

  up:
    desc: Build images, initialize toolkit, and print access URLs
    cmds:
      - task: clone
      - task: build
      - task: toolkit_init
      - 'echo "Access: http://localhost/launchpad http://localhost/project"'
